services:
  # audiobookshelf:
  #   image: ghcr.io/advplyr/audiobookshelf:latest
  #   restart: unless-stopped
  #   ports:
  #     - 13378:80
  #   volumes:
  #     - ${book}/audiobooks:/audiobooks
  #     - ${book}/podcasts:/podcasts
  #     - ${config}/config:/config
  #     - ${book}/metadata:/metadata
  #   environment:
  #     - TZ=${TZ}

  # calibre:
  #   image: lscr.io/linuxserver/calibre:latest
  #   container_name: calibre
  #   privileged: true
  #   security_opt:
  #     - seccomp:unconfined #optional
  #   environment:
  #     - PGID=${PGID}
  #     - PUID=${PUID}
  #     - TZ=${TZ}
  #   volumes:
  #     - ${config}/calibre/config:/config
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - 8080:8080
  #     - 8181:8181
  #     - 8081:8081
  #   restart: unless-stopped

  plex:
    image: 'lscr.io/linuxserver/plex'
    container_name: plex
    network_mode: host
    privileged: true
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${config}/plex:/config
      - ${tv}:/tv
      - ${movies}:/movies
      - ${config}/transcode/plex:/transcode
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu

  tdarr:
    container_name: tdarr
    image: 'ghcr.io/haveagitgat/tdarr:latest'
    restart: unless-stopped
    network_mode: bridge
    privileged: true
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=MyInternalNode
      - nodeIP=0.0.0.0
      - nodePort=8267
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${config}/tdarr/server:/app/server
      - ${config}/tdarr/config:/app/configs
      - ${config}/tdarr/logs:/app/logs
      - ${tv}:/tv
      - ${movies}:/movies
      - ${videos}:/videos
      - ${config}/transcode/tdarr:/temp
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu

networks:
  docker:
    driver: bridge