services:
  bitwarden:
    image: bitwarden/self-host:beta
    container_name: bitwarden
    hostname: bitwarden
    restart: always
    networks:
      - docker
    environment:
      - BW_DOMAIN=${BW_DOMAIN}
      - BW_DB_PROVIDER=mysql
      - BW_DB_SERVER=db
      - BW_DB_DATABASE=${BW_DB_DATABASE}
      - BW_DB_USERNAME=${BW_DB_USERNAME}
      - BW_DB_PASSWORD=${BW_DB_PASSWORD}
      - BW_INSTALLATION_ID=${BW_INSTALLATION_ID}
      - BW_INSTALLATION_KEY=${BW_INSTALLATION_KEY}
      - PUID=${PUID}
      - PGID=${PGID}
      # Yubikey
      #globalSettings__yubico__clientId=REPLACE
      #globalSettings__yubico__key=REPLACE
      # SMTP
      - globalSettings__mail__replyToEmail=no_reply@lontiotlabz.homes
      - globalSettings__mail__smtp__host=lontiotlabz.homes
      - globalSettings__mail__smtp__port=25
      - globalSettings__mail__smtp__ssl=false
    volumes:
      - ${config}/bitwarden/vault:/etc/bitwarden
    ports:
      - 80:8080
    depends_on:
      - db

  db:
    image: mariadb:10
    container_name: mariadb
    hostname: mariadb
    restart: always
    networks:
      - docker
    environment:
      MARIADB_USER: ${BW_DB_USERNAME}
      MARIADB_PASSWORD: ${BW_DB_PASSWORD}
      MARIADB_DATABASE: ${BW_DB_DATABASE}
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - ${config}/bitwarden/data:/var/lib/mysql

networks:
  docker:
    driver: bridge