- name: Create group
  ansible.builtin.group:
    name: "{{ new_user }}"
    state: present

- name: Create new user
  ansible.builtin.user:
    name: "{{ new_user }}"
    password: "{{ user_password }}"
    shell: /bin/bash
    group: "{{ new_user }}"
  tags:
    - always

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ new_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
  tags:
    - always